[project]
name = "freight-rate-prediction-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Wendirad Demelash", email = "wendiradame@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dvc>=3.67.1",
    "geopandas>=1.1.4",
    "lightgbm>=4.7.0",
    "numpy>=2.5.3",
    "openlayers>=0.1.6",
    "pandas>=3.0.5",
    "pyarrow>=13.0",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "shapely>=2.1.2",
    "statsmodels>=0.15.0",
    "vegafusion>=2.0.3",
    "vl-convert-python>=1.9.0",
    "wandb>=0.30.0",
]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["data", "experiments", "features", "models", "utils"]

[dependency-groups]
dev = [
    "marimo>=0.24.2",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
